# -*- coding: utf-8 -*-
"""Trabalho-individual1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DVt8lkpsaoQF-l-Gb-yI5L263lml9niu

# SEÇÃO 1 TRABALHO INDIVIDUAL - MÓDULO 4

**Uma determinada loja deseja produzir relatórios
semanais com ganhos e despesas. O gerente da
loja te contratou para gerar um relatório de uma
semana para mostrar ao dono da loja como a
análise dos dados pode ser útil para eles. Para
isso, ele te enviou uma tabela de exemplo das
despesas de uma semana:
CONTEXTO
Além disso, ele informou que os ganhos não estão nessa planilha, mas que ele
possui a seguinte lista: 2200, 2420.50, 3391, 5322, 4898.50, 4200, 3893
respectivos aos dias da semana. Ele te deixou bem livre para incluir no relatório as
estatísticas que desejar, mas ele deseja que o relatório contenha outros dados que
veremos a seguir.**



|Dia|Limpeza|Comida|Transporte|Outros|
|---|---|---|---|---|
|segunda|100|221.60|150|0|
|terça|0|375.31|100|0
|quarta|100|412.00|125|2310|
|quinta|0|495.20|300|500|
|sexta|100|245.00|525|0|
|sábado|100|245.00|525|0|
|domingo|0|164.00|75|820|

 CONTEXTO Além disso, ele informou que os ganhos não estão nessa planilha, mas que ele possui a seguinte lista: 2200, 2420.50, 3391, 5322, 4898.50, 4200, 3893 respectivos aos dias da semana. Ele te deixou bem livre para incluir no relatório as estatísticas que desejar, mas ele deseja que o relatório contenha outros dados que veremos a seguir.

**DATA FRAME**
---
"""

import pandas as pd
#dícionario para armanezar dados entregues pela loja
dados_semanais = {'Limpeza':[100,0,100,0,100,100,0,400.00,57.14], 'Comida':[221.60, 375.31, 412.00, 495.20, 411.53, 245.00, 164.00, 2324.64, 332.09], 'Transporte':[150,100,125,300,275,525,75,1550.00,221.43], 'Outros':[0,0,2310,500,0,0,820,3630.00,518.57], 'Ganhos':[2200, 2420.50, 3391, 5322, 4898.50, 4200, 3893, 26325, 3760.71]}
df = pd.DataFrame(dados_semanais, index = ['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo','Total','Média'])
df

"""# DIMINUIR 7%

foi feito dados de ganhos de cada dia da semana e subtraído o imposto de 7%.
"""

Ganhos_diarios = df[:7]['Ganhos']
Ganhos_diarios * 0.93

"""**TOTAL DOS GANHOS**
---

foi selecionado o total dos ganhos.
"""

Total_Ganhos = df['Ganhos']['Total']
Total_Ganhos

"""#MÉDIA DOS GANHOS SEMANAIS

foi selecionado na tabela a média do ganho semanal.
"""

Media_Ganhos = df['Ganhos']['Média']
Media_Ganhos

"""#SOMA TOTAL DAS DESPESAS

foram selecionados os valores das despesas: Limpeza, Comida, Transporte e Outros.
"""

Dados_semanais = df[['Limpeza', 'Comida', 'Transporte', 'Outros']]
Dados_semanais.loc['Total']

"""#MÉDIA SEMANAL DAS DESPESAS

selecionados os mesmos valores a cima, porém buscando a média semanal.
"""

Dados_semanais.loc['Média']

"""#LUCRO DIÁRO

cálculo com as despesas por dia e depois efetuado um cálculo com ganhos diários.
"""

df ['Lucro'] = df ['Ganhos'] - (df ['Limpeza'] + df ['Outros'] + df['Comida'] + df ['Transporte'])
df

"""#LUCRO SEMANAL

soma do total das despesas semanais e esse valor foi executado do valor ganhos semanais e revertendo o resultado.
"""

Lucro_semanais = df['Lucro']
Lucro_semanais